export interface OnboardingEmailCopy { heading:string; intro1a:string; intro1b:string; intro2:string; ctaOnboarding:string; planTitle:string; step1t:string; step1d:string; step2t:string; step2d:string; step3t:string; step3d:string; step4t:string; step4d:string; step5t:string; step5d:string; step6t:string; step6d:string; step7t:string; step7d:string; step8t:string; step8d:string; installTitle:string; installIntro:string; installAppStore:string; installTestflight:string; installApkNote:string; installWebNote:string; ctaCall:string; footer:string; footerMeeting:string; subject:string; preview:string }

export const ONBOARDING_EMAIL_COPY: Record<string, OnboardingEmailCopy> = {
  pt: {
    heading: "Bem-vindo à MoreThanMoney 👋",
    intro1a: "O teu onboarding está pronto e funcional. Segue os passos por ordem em ",
    intro1b: " e em 48 horas tens os primeiros resultados a acontecer.",
    intro2: "Vieste por cripto, UGC ou social media? Começas já no learn while you earn — a automação e os alertas trabalham enquanto exploras a tua área.",
    ctaOnboarding: "🚀 Ver o meu Onboarding",
    planTitle: "⚡ O teu plano de 48 horas",
    step1t: "Instala a app", step1d: "App Store, APK Android ou Web App — a conta é a mesma, sempre sincronizada.",
    step2t: "Cria a conta e entra", step2d: "3 dias de Premium grátis, sem cobrança. Ao fim do trial, 1.º mês por 34,99€.",
    step3t: "Ativa a automação", step3d: "Cópia automática, Tap to Trade ou Alertas — escolhe o modo certo para ti.",
    step4t: "Configura os alertas", step4d: "Ativa as notificações push das estratégias (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Aceita um Tap to Trade", step5d: "Recebes o sinal, revês os detalhes e executas na tua conta com um toque.",
    step6t: "Scanners & Ferramentas", step6d: "Gold Killer, MTM V3.4 e Sensei X + DCA diário de cripto e ETFs.",
    step7t: "Vê uma aula ao vivo", step7d: "Sessões com os educadores MTM, várias por semana, no separador Ao Vivo.",
    step8t: "Marca a tua chamada de Onboarding", step8d: "30 min com a equipa para deixar conta, automação e plano de estudo prontos.",
    installTitle: "📲 Instala a app",
    installIntro: "Escolhe a tua plataforma:",
    installAppStore: "App Store (iPhone)", installTestflight: "Beta TestFlight",
    installApkNote: "(autoriza \"fontes desconhecidas\")",
    installWebNote: "(sem instalar nada)",
    ctaCall: "📅 Marcar Onboarding (30 min)",
    footer: "Dúvidas?",
    footerMeeting: "marca uma reunião",
    subject: "O teu onboarding MTM está pronto 🚀",
    preview: "O teu onboarding MTM está pronto — o plano de 48 horas.",
  },
  en: {
    heading: "Welcome to MoreThanMoney 👋",
    intro1a: "Your onboarding is ready and up and running. Follow the steps in order in ",
    intro1b: " and in 48 hours you'll have your first results happening.",
    intro2: "Here for crypto, UGC or social media? You start right away with learn while you earn — the automation and the alerts work while you explore your area.",
    ctaOnboarding: "🚀 See my Onboarding",
    planTitle: "⚡ Your 48-hour plan",
    step1t: "Install the app", step1d: "App Store, Android APK or Web App — it's the same account, always synced.",
    step2t: "Create your account and log in", step2d: "3 days of Premium free, no charge. After the trial, 1st month for 34,99€.",
    step3t: "Turn on automation", step3d: "Automatic copy, Tap to Trade or Alerts — pick the right mode for you.",
    step4t: "Set up the alerts", step4d: "Turn on push notifications for the strategies (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Accept a Tap to Trade", step5d: "You get the signal, review the details and execute it in your account with one tap.",
    step6t: "Scanners & Tools", step6d: "Gold Killer, MTM V3.4 and Sensei X + daily DCA for crypto and ETFs.",
    step7t: "Watch a live class", step7d: "Sessions with the MTM educators, several per week, in the Live tab.",
    step8t: "Book your Onboarding call", step8d: "30 min with the team to get your account, automation and study plan ready.",
    installTitle: "📲 Install the app",
    installIntro: "Choose your platform:",
    installAppStore: "App Store (iPhone)", installTestflight: "TestFlight Beta",
    installApkNote: "(allow \"unknown sources\")",
    installWebNote: "(nothing to install)",
    ctaCall: "📅 Book Onboarding (30 min)",
    footer: "Questions?",
    footerMeeting: "book a meeting",
    subject: "Your MTM onboarding is ready 🚀",
    preview: "Your MTM onboarding is ready — the 48-hour plan.",
  },
  es: {
    heading: "Bienvenido a MoreThanMoney 👋",
    intro1a: "Tu onboarding está listo y funcionando. Sigue los pasos en orden en ",
    intro1b: " y en 48 horas tienes los primeros resultados en marcha.",
    intro2: "¿Vienes por cripto, UGC o social media? Empiezas ya con el learn while you earn — la automatización y las alertas trabajan mientras exploras tu área.",
    ctaOnboarding: "🚀 Ver mi Onboarding",
    planTitle: "⚡ Tu plan de 48 horas",
    step1t: "Instala la app", step1d: "App Store, APK de Android o Web App — la cuenta es la misma, siempre sincronizada.",
    step2t: "Crea la cuenta y entra", step2d: "3 días de Premium gratis, sin cobro. Al terminar la prueba, 1.er mes por 34,99€.",
    step3t: "Activa la automatización", step3d: "Copia automática, Tap to Trade o Alertas — elige el modo adecuado para ti.",
    step4t: "Configura las alertas", step4d: "Activa las notificaciones push de las estrategias (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Acepta un Tap to Trade", step5d: "Recibes la señal, revisas los detalles y la ejecutas en tu cuenta con un toque.",
    step6t: "Scanners y Herramientas", step6d: "Gold Killer, MTM V3.4 y Sensei X + DCA diario de cripto y ETFs.",
    step7t: "Mira una clase en vivo", step7d: "Sesiones con los educadores MTM, varias por semana, en la pestaña En Vivo.",
    step8t: "Reserva tu llamada de Onboarding", step8d: "30 min con el equipo para dejar la cuenta, la automatización y el plan de estudio listos.",
    installTitle: "📲 Instala la app",
    installIntro: "Elige tu plataforma:",
    installAppStore: "App Store (iPhone)", installTestflight: "Beta de TestFlight",
    installApkNote: "(autoriza \"fuentes desconocidas\")",
    installWebNote: "(sin instalar nada)",
    ctaCall: "📅 Reservar Onboarding (30 min)",
    footer: "¿Dudas?",
    footerMeeting: "reserva una reunión",
    subject: "Tu onboarding MTM está listo 🚀",
    preview: "Tu onboarding MTM está listo — el plan de 48 horas.",
  },
  fr: {
    heading: "Bienvenue chez MoreThanMoney 👋",
    intro1a: "Ton onboarding est prêt et opérationnel. Suis les étapes dans l'ordre dans ",
    intro1b: " et en 48 heures tes premiers résultats commencent à arriver.",
    intro2: "Tu viens pour la crypto, l'UGC ou les social media ? Tu commences tout de suite avec le learn while you earn — l'automatisation et les alertes travaillent pendant que tu explores ton domaine.",
    ctaOnboarding: "🚀 Voir mon Onboarding",
    planTitle: "⚡ Ton plan de 48 heures",
    step1t: "Installe l'app", step1d: "App Store, APK Android ou Web App — c'est le même compte, toujours synchronisé.",
    step2t: "Crée ton compte et connecte-toi", step2d: "3 jours de Premium gratuits, sans prélèvement. À la fin de l'essai, 1er mois à 34,99€.",
    step3t: "Active l'automatisation", step3d: "Copie automatique, Tap to Trade ou Alertes — choisis le mode qui te convient.",
    step4t: "Configure les alertes", step4d: "Active les notifications push des stratégies (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Accepte un Tap to Trade", step5d: "Tu reçois le signal, tu vérifies les détails et tu l'exécutes sur ton compte d'un seul toucher.",
    step6t: "Scanners & Outils", step6d: "Gold Killer, MTM V3.4 et Sensei X + DCA quotidien de crypto et d'ETFs.",
    step7t: "Regarde un cours en direct", step7d: "Des sessions avec les éducateurs MTM, plusieurs par semaine, dans l'onglet En Direct.",
    step8t: "Réserve ton appel d'Onboarding", step8d: "30 min avec l'équipe pour préparer ton compte, ton automatisation et ton plan d'étude.",
    installTitle: "📲 Installe l'app",
    installIntro: "Choisis ta plateforme :",
    installAppStore: "App Store (iPhone)", installTestflight: "Bêta TestFlight",
    installApkNote: "(autorise les « sources inconnues »)",
    installWebNote: "(rien à installer)",
    ctaCall: "📅 Réserver l'Onboarding (30 min)",
    footer: "Des questions ?",
    footerMeeting: "réserve une réunion",
    subject: "Ton onboarding MTM est prêt 🚀",
    preview: "Ton onboarding MTM est prêt — le plan de 48 heures.",
  },
  de: {
    heading: "Willkommen bei MoreThanMoney 👋",
    intro1a: "Dein Onboarding ist fertig und einsatzbereit. Folge den Schritten der Reihe nach in ",
    intro1b: " und in 48 Stunden hast du deine ersten Ergebnisse.",
    intro2: "Du kommst wegen Krypto, UGC oder Social Media? Du startest sofort mit dem learn while you earn — die Automatisierung und die Alerts arbeiten, während du deinen Bereich erkundest.",
    ctaOnboarding: "🚀 Mein Onboarding ansehen",
    planTitle: "⚡ Dein 48-Stunden-Plan",
    step1t: "Installiere die App", step1d: "App Store, Android-APK oder Web App — es ist dasselbe Konto, immer synchronisiert.",
    step2t: "Erstelle dein Konto und melde dich an", step2d: "3 Tage Premium gratis, ohne Abbuchung. Nach dem Trial 1. Monat für 34,99€.",
    step3t: "Aktiviere die Automatisierung", step3d: "Automatisches Kopieren, Tap to Trade oder Alerts — wähle den richtigen Modus für dich.",
    step4t: "Richte die Alerts ein", step4d: "Aktiviere die Push-Benachrichtigungen der Strategien (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Nimm einen Tap to Trade an", step5d: "Du bekommst das Signal, prüfst die Details und führst es mit einem Tipp auf deinem Konto aus.",
    step6t: "Scanner & Tools", step6d: "Gold Killer, MTM V3.4 und Sensei X + täglicher DCA für Krypto und ETFs.",
    step7t: "Sieh dir eine Live-Klasse an", step7d: "Sessions mit den MTM-Educatoren, mehrmals pro Woche, im Tab Live.",
    step8t: "Buche deinen Onboarding-Call", step8d: "30 min mit dem Team, um Konto, Automatisierung und Lernplan startklar zu machen.",
    installTitle: "📲 Installiere die App",
    installIntro: "Wähle deine Plattform:",
    installAppStore: "App Store (iPhone)", installTestflight: "TestFlight Beta",
    installApkNote: "(erlaube „unbekannte Quellen“)",
    installWebNote: "(nichts zu installieren)",
    ctaCall: "📅 Onboarding buchen (30 min)",
    footer: "Fragen?",
    footerMeeting: "buche ein Meeting",
    subject: "Dein MTM-Onboarding ist fertig 🚀",
    preview: "Dein MTM-Onboarding ist fertig — der 48-Stunden-Plan.",
  },
  it: {
    heading: "Benvenuto in MoreThanMoney 👋",
    intro1a: "Il tuo onboarding è pronto e funzionante. Segui i passi in ordine in ",
    intro1b: " e in 48 ore hai i primi risultati che iniziano ad arrivare.",
    intro2: "Sei qui per la cripto, l'UGC o i social media? Inizi subito con il learn while you earn — l'automazione e gli alert lavorano mentre esplori la tua area.",
    ctaOnboarding: "🚀 Vedi il mio Onboarding",
    planTitle: "⚡ Il tuo piano di 48 ore",
    step1t: "Installa l'app", step1d: "App Store, APK Android o Web App — l'account è lo stesso, sempre sincronizzato.",
    step2t: "Crea l'account ed entra", step2d: "3 giorni di Premium gratis, senza addebito. Alla fine del trial, 1° mese a 34,99€.",
    step3t: "Attiva l'automazione", step3d: "Copia automatica, Tap to Trade o Alert — scegli la modalità giusta per te.",
    step4t: "Configura gli alert", step4d: "Attiva le notifiche push delle strategie (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Accetta un Tap to Trade", step5d: "Ricevi il segnale, controlli i dettagli e lo esegui sul tuo account con un tocco.",
    step6t: "Scanner e Strumenti", step6d: "Gold Killer, MTM V3.4 e Sensei X + DCA giornaliero di cripto ed ETF.",
    step7t: "Guarda una lezione dal vivo", step7d: "Sessioni con gli educatori MTM, diverse a settimana, nella scheda Dal Vivo.",
    step8t: "Prenota la tua chiamata di Onboarding", step8d: "30 min con il team per preparare account, automazione e piano di studio.",
    installTitle: "📲 Installa l'app",
    installIntro: "Scegli la tua piattaforma:",
    installAppStore: "App Store (iPhone)", installTestflight: "Beta TestFlight",
    installApkNote: "(autorizza le \"fonti sconosciute\")",
    installWebNote: "(senza installare niente)",
    ctaCall: "📅 Prenota Onboarding (30 min)",
    footer: "Domande?",
    footerMeeting: "prenota una riunione",
    subject: "Il tuo onboarding MTM è pronto 🚀",
    preview: "Il tuo onboarding MTM è pronto — il piano di 48 ore.",
  },
  nl: {
    heading: "Welkom bij MoreThanMoney 👋",
    intro1a: "Je onboarding is klaar en werkt. Volg de stappen op volgorde in ",
    intro1b: " en binnen 48 uur zie je je eerste resultaten.",
    intro2: "Kom je voor crypto, UGC of social media? Je begint meteen met learn while you earn — de automatisering en de alerts werken terwijl jij je gebied verkent.",
    ctaOnboarding: "🚀 Bekijk mijn Onboarding",
    planTitle: "⚡ Jouw 48-uursplan",
    step1t: "Installeer de app", step1d: "App Store, Android-APK of Web App — het is hetzelfde account, altijd gesynchroniseerd.",
    step2t: "Maak je account aan en log in", step2d: "3 dagen Premium gratis, zonder kosten. Na de trial 1e maand voor 34,99€.",
    step3t: "Zet de automatisering aan", step3d: "Automatisch kopiëren, Tap to Trade of Alerts — kies de modus die bij je past.",
    step4t: "Stel de alerts in", step4d: "Zet de push-meldingen van de strategieën aan (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Accepteer een Tap to Trade", step5d: "Je krijgt het signaal, bekijkt de details en voert het met één tik uit op je account.",
    step6t: "Scanners & Tools", step6d: "Gold Killer, MTM V3.4 en Sensei X + dagelijkse DCA voor crypto en ETF's.",
    step7t: "Bekijk een live les", step7d: "Sessies met de MTM-educators, meerdere per week, in het tabblad Live.",
    step8t: "Plan je Onboarding-gesprek", step8d: "30 min met het team om je account, automatisering en studieplan klaar te zetten.",
    installTitle: "📲 Installeer de app",
    installIntro: "Kies je platform:",
    installAppStore: "App Store (iPhone)", installTestflight: "TestFlight-bèta",
    installApkNote: "(sta \"onbekende bronnen\" toe)",
    installWebNote: "(niets te installeren)",
    ctaCall: "📅 Onboarding plannen (30 min)",
    footer: "Vragen?",
    footerMeeting: "plan een afspraak",
    subject: "Je MTM-onboarding is klaar 🚀",
    preview: "Je MTM-onboarding is klaar — het 48-uursplan.",
  },
  "zh-CN": {
    heading: "欢迎加入 MoreThanMoney 👋",
    intro1a: "你的 onboarding 已经准备就绪并可以使用。按顺序完成 ",
    intro1b: " 中的步骤，48 小时内你就能看到第一批结果。",
    intro2: "你是因为加密货币、UGC 还是 social media 而来？你现在就从 learn while you earn 开始 —— 自动化和提醒会在你探索自己领域的同时为你工作。",
    ctaOnboarding: "🚀 查看我的 Onboarding",
    planTitle: "⚡ 你的 48 小时计划",
    step1t: "安装 app", step1d: "App Store、Android APK 或 Web App —— 账户是同一个，始终同步。",
    step2t: "创建账户并登录", step2d: "3 天 Premium 免费，不收费。试用结束后，第 1 个月 34,99€。",
    step3t: "开启自动化", step3d: "自动跟单、Tap to Trade 或提醒 —— 选择最适合你的模式。",
    step4t: "设置提醒", step4d: "开启各策略的推送通知（Premium、Forex、Sensei、GoldKiller）。",
    step5t: "接受一个 Tap to Trade", step5d: "你收到信号，查看细节，一键在自己的账户上执行。",
    step6t: "扫描器和工具", step6d: "Gold Killer、MTM V3.4 和 Sensei X + 每日加密货币和 ETF 的 DCA。",
    step7t: "观看一节直播课", step7d: "与 MTM 教育者的课程，每周多场，在直播标签页中。",
    step8t: "预约你的 Onboarding 通话", step8d: "与团队 30 min，把账户、自动化和学习计划都准备好。",
    installTitle: "📲 安装 app",
    installIntro: "选择你的平台：",
    installAppStore: "App Store（iPhone）", installTestflight: "TestFlight 测试版",
    installApkNote: "（允许“未知来源”）",
    installWebNote: "（无需安装任何东西）",
    ctaCall: "📅 预约 Onboarding（30 min）",
    footer: "有疑问？",
    footerMeeting: "预约一次会议",
    subject: "你的 MTM onboarding 已准备就绪 🚀",
    preview: "你的 MTM onboarding 已准备就绪 —— 48 小时计划。",
  },
  ja: {
    heading: "MoreThanMoney へようこそ 👋",
    intro1a: "オンボーディングの準備が整い、すぐに使えます。",
    intro1b: " で手順を順番に進めれば、48 時間で最初の結果が出始めます。",
    intro2: "暗号資産、UGC、social media のいずれかで来ましたか？今すぐ learn while you earn を始めましょう —— あなたが自分の分野を探る間、自動化とアラートが働きます。",
    ctaOnboarding: "🚀 マイ Onboarding を見る",
    planTitle: "⚡ あなたの 48 時間プラン",
    step1t: "app をインストール", step1d: "App Store、Android APK、または Web App —— アカウントは同じで、常に同期されます。",
    step2t: "アカウントを作成してログイン", step2d: "3 日間 Premium 無料、請求なし。トライアル終了後、初月は 34,99€。",
    step3t: "自動化をオンにする", step3d: "自動コピー、Tap to Trade、またはアラート —— あなたに合ったモードを選びましょう。",
    step4t: "アラートを設定", step4d: "各戦略のプッシュ通知をオンにします（Premium、Forex、Sensei、GoldKiller）。",
    step5t: "Tap to Trade を受け入れる", step5d: "シグナルを受け取り、詳細を確認して、ワンタップで自分のアカウントで実行します。",
    step6t: "スキャナーとツール", step6d: "Gold Killer、MTM V3.4、Sensei X + 暗号資産と ETF の毎日の DCA。",
    step7t: "ライブ授業を見る", step7d: "MTM の教育者によるセッション、週に数回、ライブタブで。",
    step8t: "Onboarding コールを予約", step8d: "チームと 30 min、アカウント・自動化・学習プランを整えます。",
    installTitle: "📲 app をインストール",
    installIntro: "プラットフォームを選んでください：",
    installAppStore: "App Store（iPhone）", installTestflight: "TestFlight ベータ",
    installApkNote: "（「不明なソース」を許可）",
    installWebNote: "（何もインストール不要）",
    ctaCall: "📅 Onboarding を予約（30 min）",
    footer: "ご質問は？",
    footerMeeting: "ミーティングを予約",
    subject: "あなたの MTM オンボーディングの準備が整いました 🚀",
    preview: "あなたの MTM オンボーディングの準備が整いました —— 48 時間プラン。",
  },
  ar: {
    heading: "مرحبًا بك في MoreThanMoney 👋",
    intro1a: "الـ onboarding الخاص بك جاهز ويعمل. اتبع الخطوات بالترتيب في ",
    intro1b: " وخلال 48 ساعة تبدأ أولى نتائجك في الظهور.",
    intro2: "جئت من أجل الكريبتو أو UGC أو social media؟ تبدأ فورًا مع learn while you earn — الأتمتة والتنبيهات تعمل بينما تستكشف مجالك.",
    ctaOnboarding: "🚀 عرض الـ Onboarding الخاص بي",
    planTitle: "⚡ خطتك لمدة 48 ساعة",
    step1t: "ثبّت الـ app", step1d: "App Store أو APK لأندرويد أو Web App — الحساب نفسه، متزامن دائمًا.",
    step2t: "أنشئ الحساب وسجّل الدخول", step2d: "3 أيام Premium مجانًا، دون أي رسوم. بعد انتهاء الفترة التجريبية، الشهر الأول بـ 34,99€.",
    step3t: "فعّل الأتمتة", step3d: "النسخ التلقائي أو Tap to Trade أو التنبيهات — اختر الوضع المناسب لك.",
    step4t: "اضبط التنبيهات", step4d: "فعّل إشعارات الدفع للاستراتيجيات (Premium، Forex، Sensei، GoldKiller).",
    step5t: "اقبل Tap to Trade", step5d: "تستلم الإشارة، تراجع التفاصيل، وتنفّذها في حسابك بلمسة واحدة.",
    step6t: "الماسحات والأدوات", step6d: "Gold Killer وMTM V3.4 وSensei X + DCA يومي للكريبتو وETF.",
    step7t: "شاهد حصة مباشرة", step7d: "جلسات مع مدرّبي MTM، عدة مرات أسبوعيًا، في تبويب البث المباشر.",
    step8t: "احجز مكالمة الـ Onboarding", step8d: "30 min مع الفريق لتجهيز الحساب والأتمتة وخطة الدراسة.",
    installTitle: "📲 ثبّت الـ app",
    installIntro: "اختر منصتك:",
    installAppStore: "App Store (iPhone)", installTestflight: "نسخة TestFlight التجريبية",
    installApkNote: "(اسمح بـ \"المصادر غير المعروفة\")",
    installWebNote: "(دون تثبيت أي شيء)",
    ctaCall: "📅 احجز Onboarding (30 min)",
    footer: "أسئلة؟",
    footerMeeting: "احجز اجتماعًا",
    subject: "الـ onboarding الخاص بك في MTM جاهز 🚀",
    preview: "الـ onboarding الخاص بك في MTM جاهز — خطة الـ 48 ساعة.",
  },
  ru: {
    heading: "Добро пожаловать в MoreThanMoney 👋",
    intro1a: "Твой onboarding готов и работает. Выполняй шаги по порядку в ",
    intro1b: " и через 48 часов у тебя пойдут первые результаты.",
    intro2: "Пришёл ради крипты, UGC или social media? Начинаешь сразу с learn while you earn — автоматизация и оповещения работают, пока ты изучаешь свою область.",
    ctaOnboarding: "🚀 Открыть мой Onboarding",
    planTitle: "⚡ Твой план на 48 часов",
    step1t: "Установи app", step1d: "App Store, Android APK или Web App — аккаунт один и тот же, всегда синхронизирован.",
    step2t: "Создай аккаунт и войди", step2d: "3 дня Premium бесплатно, без списаний. После пробного периода 1-й месяц за 34,99€.",
    step3t: "Включи автоматизацию", step3d: "Автокопирование, Tap to Trade или Оповещения — выбери подходящий тебе режим.",
    step4t: "Настрой оповещения", step4d: "Включи push-уведомления по стратегиям (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Прими Tap to Trade", step5d: "Получаешь сигнал, проверяешь детали и исполняешь его в своём аккаунте одним касанием.",
    step6t: "Сканеры и инструменты", step6d: "Gold Killer, MTM V3.4 и Sensei X + ежедневный DCA по крипте и ETF.",
    step7t: "Посмотри живой урок", step7d: "Сессии с преподавателями MTM, несколько раз в неделю, во вкладке Живой эфир.",
    step8t: "Забронируй свой Onboarding-звонок", step8d: "30 min с командой, чтобы подготовить аккаунт, автоматизацию и план обучения.",
    installTitle: "📲 Установи app",
    installIntro: "Выбери свою платформу:",
    installAppStore: "App Store (iPhone)", installTestflight: "Бета TestFlight",
    installApkNote: "(разреши \"неизвестные источники\")",
    installWebNote: "(ничего не устанавливая)",
    ctaCall: "📅 Забронировать Onboarding (30 min)",
    footer: "Вопросы?",
    footerMeeting: "забронируй встречу",
    subject: "Твой onboarding MTM готов 🚀",
    preview: "Твой onboarding MTM готов — план на 48 часов.",
  },
  hi: {
    heading: "MoreThanMoney में आपका स्वागत है 👋",
    intro1a: "आपका onboarding तैयार है और चालू है। इसमें क्रम से चरणों का पालन करें ",
    intro1b: " और 48 घंटों में आपके पहले नतीजे आने लगेंगे।",
    intro2: "क्या आप crypto, UGC या social media के लिए आए हैं? आप अभी से learn while you earn शुरू करते हैं — जब आप अपना क्षेत्र एक्सप्लोर करते हैं, तब ऑटोमेशन और अलर्ट काम करते रहते हैं।",
    ctaOnboarding: "🚀 मेरा Onboarding देखें",
    planTitle: "⚡ आपकी 48 घंटे की योजना",
    step1t: "app इंस्टॉल करें", step1d: "App Store, Android APK या Web App — अकाउंट वही रहता है, हमेशा सिंक्ड।",
    step2t: "अकाउंट बनाएं और लॉग इन करें", step2d: "3 दिन Premium मुफ़्त, कोई शुल्क नहीं। ट्रायल के बाद, पहला महीना 34,99€ में।",
    step3t: "ऑटोमेशन चालू करें", step3d: "ऑटोमैटिक कॉपी, Tap to Trade या अलर्ट — अपने लिए सही मोड चुनें।",
    step4t: "अलर्ट सेट करें", step4d: "रणनीतियों के push नोटिफिकेशन चालू करें (Premium, Forex, Sensei, GoldKiller)।",
    step5t: "एक Tap to Trade स्वीकार करें", step5d: "आपको सिग्नल मिलता है, आप विवरण देखते हैं और एक टैप में अपने अकाउंट पर इसे एक्ज़ीक्यूट करते हैं।",
    step6t: "स्कैनर और टूल्स", step6d: "Gold Killer, MTM V3.4 और Sensei X + crypto और ETF का रोज़ाना DCA।",
    step7t: "एक लाइव क्लास देखें", step7d: "MTM एजुकेटर्स के साथ सेशन, हफ़्ते में कई बार, लाइव टैब में।",
    step8t: "अपनी Onboarding कॉल बुक करें", step8d: "टीम के साथ 30 min, ताकि अकाउंट, ऑटोमेशन और स्टडी प्लान तैयार हो जाएं।",
    installTitle: "📲 app इंस्टॉल करें",
    installIntro: "अपना प्लेटफ़ॉर्म चुनें:",
    installAppStore: "App Store (iPhone)", installTestflight: "TestFlight बीटा",
    installApkNote: "(\"अज्ञात स्रोत\" की अनुमति दें)",
    installWebNote: "(कुछ भी इंस्टॉल किए बिना)",
    ctaCall: "📅 Onboarding बुक करें (30 min)",
    footer: "सवाल?",
    footerMeeting: "एक मीटिंग बुक करें",
    subject: "आपका MTM onboarding तैयार है 🚀",
    preview: "आपका MTM onboarding तैयार है — 48 घंटे की योजना।",
  },
  sr: {
    heading: "Dobro došao u MoreThanMoney 👋",
    intro1a: "Tvoj onboarding je spreman i funkcionalan. Prati korake redom u ",
    intro1b: " i za 48 sati počinju tvoji prvi rezultati.",
    intro2: "Došao si zbog kripta, UGC-a ili social media? Odmah krećeš sa learn while you earn — automatizacija i alertovi rade dok istražuješ svoju oblast.",
    ctaOnboarding: "🚀 Pogledaj moj Onboarding",
    planTitle: "⚡ Tvoj plan za 48 sati",
    step1t: "Instaliraj app", step1d: "App Store, Android APK ili Web App — nalog je isti, uvek sinhronizovan.",
    step2t: "Napravi nalog i uđi", step2d: "3 dana Premium besplatno, bez naplate. Po isteku triala, 1. mesec za 34,99€.",
    step3t: "Uključi automatizaciju", step3d: "Automatsko kopiranje, Tap to Trade ili Alertovi — izaberi pravi režim za sebe.",
    step4t: "Podesi alertove", step4d: "Uključi push obaveštenja za strategije (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Prihvati Tap to Trade", step5d: "Dobiješ signal, pregledaš detalje i izvršiš ga na svom nalogu jednim dodirom.",
    step6t: "Skeneri i alati", step6d: "Gold Killer, MTM V3.4 i Sensei X + dnevni DCA za kripto i ETF-ove.",
    step7t: "Pogledaj čas uživo", step7d: "Sesije sa MTM edukatorima, više puta nedeljno, u kartici Uživo.",
    step8t: "Zakaži svoj Onboarding poziv", step8d: "30 min sa timom da nalog, automatizacija i plan učenja budu spremni.",
    installTitle: "📲 Instaliraj app",
    installIntro: "Izaberi svoju platformu:",
    installAppStore: "App Store (iPhone)", installTestflight: "TestFlight Beta",
    installApkNote: "(dozvoli \"nepoznate izvore\")",
    installWebNote: "(bez instaliranja bilo čega)",
    ctaCall: "📅 Zakaži Onboarding (30 min)",
    footer: "Pitanja?",
    footerMeeting: "zakaži sastanak",
    subject: "Tvoj MTM onboarding je spreman 🚀",
    preview: "Tvoj MTM onboarding je spreman — plan za 48 sati.",
  },
  hr: {
    heading: "Dobro došao u MoreThanMoney 👋",
    intro1a: "Tvoj onboarding je spreman i funkcionalan. Slijedi korake redom u ",
    intro1b: " i za 48 sati kreću tvoji prvi rezultati.",
    intro2: "Došao si zbog kripta, UGC-a ili social media? Odmah kreneš sa learn while you earn — automatizacija i upozorenja rade dok istražuješ svoje područje.",
    ctaOnboarding: "🚀 Pogledaj svoj Onboarding",
    planTitle: "⚡ Tvoj plan za 48 sati",
    step1t: "Instaliraj app", step1d: "App Store, Android APK ili Web App — račun je isti, uvijek sinkroniziran.",
    step2t: "Napravi račun i uđi", step2d: "3 dana Premium besplatno, bez naplate. Nakon probnog razdoblja, 1. mjesec za 34,99€.",
    step3t: "Uključi automatizaciju", step3d: "Automatsko kopiranje, Tap to Trade ili Upozorenja — odaberi pravi način za sebe.",
    step4t: "Postavi upozorenja", step4d: "Uključi push obavijesti za strategije (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Prihvati Tap to Trade", step5d: "Dobiješ signal, pregledaš detalje i izvršiš ga na svom računu jednim dodirom.",
    step6t: "Skeneri i alati", step6d: "Gold Killer, MTM V3.4 i Sensei X + dnevni DCA za kripto i ETF-ove.",
    step7t: "Pogledaj predavanje uživo", step7d: "Sesije s MTM edukatorima, više puta tjedno, u kartici Uživo.",
    step8t: "Rezerviraj svoj Onboarding poziv", step8d: "30 min s timom da račun, automatizacija i plan učenja budu spremni.",
    installTitle: "📲 Instaliraj app",
    installIntro: "Odaberi svoju platformu:",
    installAppStore: "App Store (iPhone)", installTestflight: "TestFlight Beta",
    installApkNote: "(dopusti \"nepoznate izvore\")",
    installWebNote: "(bez instaliranja ičega)",
    ctaCall: "📅 Rezerviraj Onboarding (30 min)",
    footer: "Pitanja?",
    footerMeeting: "rezerviraj sastanak",
    subject: "Tvoj MTM onboarding je spreman 🚀",
    preview: "Tvoj MTM onboarding je spreman — plan za 48 sati.",
  },
  bs: {
    heading: "Dobro došao u MoreThanMoney 👋",
    intro1a: "Tvoj onboarding je spreman i funkcionalan. Prati korake redom u ",
    intro1b: " i za 48 sati kreću tvoji prvi rezultati.",
    intro2: "Došao si zbog kripta, UGC-a ili social media? Odmah kreneš sa learn while you earn — automatizacija i upozorenja rade dok istražuješ svoju oblast.",
    ctaOnboarding: "🚀 Pogledaj svoj Onboarding",
    planTitle: "⚡ Tvoj plan za 48 sati",
    step1t: "Instaliraj app", step1d: "App Store, Android APK ili Web App — račun je isti, uvijek sinhronizovan.",
    step2t: "Napravi račun i uđi", step2d: "3 dana Premium besplatno, bez naplate. Nakon probnog perioda, 1. mjesec za 34,99€.",
    step3t: "Uključi automatizaciju", step3d: "Automatsko kopiranje, Tap to Trade ili Upozorenja — odaberi pravi način za sebe.",
    step4t: "Podesi upozorenja", step4d: "Uključi push obavijesti za strategije (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Prihvati Tap to Trade", step5d: "Dobiješ signal, pregledaš detalje i izvršiš ga na svom računu jednim dodirom.",
    step6t: "Skeneri i alati", step6d: "Gold Killer, MTM V3.4 i Sensei X + dnevni DCA za kripto i ETF-ove.",
    step7t: "Pogledaj čas uživo", step7d: "Sesije s MTM edukatorima, više puta sedmično, u kartici Uživo.",
    step8t: "Zakaži svoj Onboarding poziv", step8d: "30 min s timom da račun, automatizacija i plan učenja budu spremni.",
    installTitle: "📲 Instaliraj app",
    installIntro: "Odaberi svoju platformu:",
    installAppStore: "App Store (iPhone)", installTestflight: "TestFlight Beta",
    installApkNote: "(dozvoli \"nepoznate izvore\")",
    installWebNote: "(bez instaliranja bilo čega)",
    ctaCall: "📅 Zakaži Onboarding (30 min)",
    footer: "Pitanja?",
    footerMeeting: "zakaži sastanak",
    subject: "Tvoj MTM onboarding je spreman 🚀",
    preview: "Tvoj MTM onboarding je spreman — plan za 48 sati.",
  },
  sq: {
    heading: "Mirë se erdhe në MoreThanMoney 👋",
    intro1a: "Onboarding-u yt është gati dhe funksional. Ndiq hapat me radhë te ",
    intro1b: " dhe brenda 48 orëve fillojnë rezultatet e tua të para.",
    intro2: "Erdhe për kripto, UGC ose social media? Fillon menjëherë me learn while you earn — automatizimi dhe alertet punojnë ndërsa ti eksploron fushën tënde.",
    ctaOnboarding: "🚀 Shiko Onboarding-un tim",
    planTitle: "⚡ Plani yt për 48 orë",
    step1t: "Instalo app-in", step1d: "App Store, APK Android ose Web App — llogaria është e njëjta, gjithmonë e sinkronizuar.",
    step2t: "Krijo llogarinë dhe hyr", step2d: "3 ditë Premium falas, pa asnjë tarifë. Në fund të provës, muaji i 1-rë për 34,99€.",
    step3t: "Aktivizo automatizimin", step3d: "Kopjim automatik, Tap to Trade ose Alerte — zgjidh mënyrën e duhur për ty.",
    step4t: "Konfiguro alertet", step4d: "Aktivizo njoftimet push të strategjive (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Prano një Tap to Trade", step5d: "Merr sinjalin, shqyrton detajet dhe e ekzekuton në llogarinë tënde me një prekje.",
    step6t: "Skanerë dhe Mjete", step6d: "Gold Killer, MTM V3.4 dhe Sensei X + DCA ditor për kripto dhe ETF.",
    step7t: "Shiko një mësim live", step7d: "Sesione me edukatorët e MTM, disa herë në javë, te skeda Live.",
    step8t: "Rezervo telefonatën tënde të Onboarding", step8d: "30 min me ekipin për të përgatitur llogarinë, automatizimin dhe planin e studimit.",
    installTitle: "📲 Instalo app-in",
    installIntro: "Zgjidh platformën tënde:",
    installAppStore: "App Store (iPhone)", installTestflight: "Beta TestFlight",
    installApkNote: "(lejo \"burimet e panjohura\")",
    installWebNote: "(pa instaluar asgjë)",
    ctaCall: "📅 Rezervo Onboarding (30 min)",
    footer: "Pyetje?",
    footerMeeting: "rezervo një takim",
    subject: "Onboarding-u yt MTM është gati 🚀",
    preview: "Onboarding-u yt MTM është gati — plani për 48 orë.",
  },
  bg: {
    heading: "Добре дошъл в MoreThanMoney 👋",
    intro1a: "Твоят onboarding е готов и работи. Следвай стъпките по ред в ",
    intro1b: " и за 48 часа започват първите ти резултати.",
    intro2: "Дойде заради крипто, UGC или social media? Започваш веднага с learn while you earn — автоматизацията и известията работят, докато проучваш своята област.",
    ctaOnboarding: "🚀 Виж моя Onboarding",
    planTitle: "⚡ Твоят план за 48 часа",
    step1t: "Инсталирай app", step1d: "App Store, Android APK или Web App — акаунтът е същият, винаги синхронизиран.",
    step2t: "Създай акаунт и влез", step2d: "3 дни Premium безплатно, без таксуване. След края на пробния период, 1-ви месец за 34,99€.",
    step3t: "Включи автоматизацията", step3d: "Автоматично копиране, Tap to Trade или Известия — избери правилния режим за теб.",
    step4t: "Настрой известията", step4d: "Включи push известията на стратегиите (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Приеми Tap to Trade", step5d: "Получаваш сигнала, преглеждаш детайлите и го изпълняваш в акаунта си с едно докосване.",
    step6t: "Скенери и инструменти", step6d: "Gold Killer, MTM V3.4 и Sensei X + ежедневен DCA за крипто и ETF.",
    step7t: "Гледай урок на живо", step7d: "Сесии с преподавателите на MTM, няколко пъти седмично, в раздела На живо.",
    step8t: "Резервирай своя Onboarding разговор", step8d: "30 min с екипа, за да са готови акаунтът, автоматизацията и планът за учене.",
    installTitle: "📲 Инсталирай app",
    installIntro: "Избери своята платформа:",
    installAppStore: "App Store (iPhone)", installTestflight: "TestFlight бета",
    installApkNote: "(разреши \"неизвестни източници\")",
    installWebNote: "(без да инсталираш нищо)",
    ctaCall: "📅 Резервирай Onboarding (30 min)",
    footer: "Въпроси?",
    footerMeeting: "резервирай среща",
    subject: "Твоят MTM onboarding е готов 🚀",
    preview: "Твоят MTM onboarding е готов — планът за 48 часа.",
  },
  ro: {
    heading: "Bine ai venit la MoreThanMoney 👋",
    intro1a: "Onboarding-ul tău este gata și funcțional. Urmează pașii în ordine în ",
    intro1b: " și în 48 de ore încep primele tale rezultate.",
    intro2: "Ai venit pentru cripto, UGC sau social media? Începi imediat cu learn while you earn — automatizarea și alertele lucrează în timp ce îți explorezi domeniul.",
    ctaOnboarding: "🚀 Vezi Onboarding-ul meu",
    planTitle: "⚡ Planul tău de 48 de ore",
    step1t: "Instalează app-ul", step1d: "App Store, APK Android sau Web App — contul este același, mereu sincronizat.",
    step2t: "Creează contul și intră", step2d: "3 zile Premium gratuit, fără taxare. La finalul trialului, prima lună la 34,99€.",
    step3t: "Activează automatizarea", step3d: "Copiere automată, Tap to Trade sau Alerte — alege modul potrivit pentru tine.",
    step4t: "Configurează alertele", step4d: "Activează notificările push ale strategiilor (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Acceptă un Tap to Trade", step5d: "Primești semnalul, verifici detaliile și îl execuți în contul tău cu o atingere.",
    step6t: "Scanere și Instrumente", step6d: "Gold Killer, MTM V3.4 și Sensei X + DCA zilnic pentru cripto și ETF-uri.",
    step7t: "Urmărește o lecție live", step7d: "Sesiuni cu educatorii MTM, de mai multe ori pe săptămână, în tabul Live.",
    step8t: "Rezervă-ți apelul de Onboarding", step8d: "30 min cu echipa pentru a-ți pregăti contul, automatizarea și planul de studiu.",
    installTitle: "📲 Instalează app-ul",
    installIntro: "Alege-ți platforma:",
    installAppStore: "App Store (iPhone)", installTestflight: "Beta TestFlight",
    installApkNote: "(permite \"surse necunoscute\")",
    installWebNote: "(fără să instalezi nimic)",
    ctaCall: "📅 Rezervă Onboarding (30 min)",
    footer: "Întrebări?",
    footerMeeting: "rezervă o întâlnire",
    subject: "Onboarding-ul tău MTM este gata 🚀",
    preview: "Onboarding-ul tău MTM este gata — planul de 48 de ore.",
  },
  pl: {
    heading: "Witaj w MoreThanMoney 👋",
    intro1a: "Twój onboarding jest gotowy i działa. Wykonuj kroki po kolei w ",
    intro1b: " a w 48 godzin pojawią się Twoje pierwsze wyniki.",
    intro2: "Przyszedłeś po krypto, UGC albo social media? Zaczynasz od razu od learn while you earn — automatyzacja i alerty działają, gdy Ty poznajesz swój obszar.",
    ctaOnboarding: "🚀 Zobacz mój Onboarding",
    planTitle: "⚡ Twój plan na 48 godzin",
    step1t: "Zainstaluj app", step1d: "App Store, APK na Androida lub Web App — to samo konto, zawsze zsynchronizowane.",
    step2t: "Załóż konto i zaloguj się", step2d: "3 dni Premium za darmo, bez opłat. Po okresie próbnym 1. miesiąc za 34,99€.",
    step3t: "Włącz automatyzację", step3d: "Automatyczne kopiowanie, Tap to Trade lub Alerty — wybierz tryb odpowiedni dla siebie.",
    step4t: "Skonfiguruj alerty", step4d: "Włącz powiadomienia push dla strategii (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Zaakceptuj Tap to Trade", step5d: "Dostajesz sygnał, sprawdzasz szczegóły i wykonujesz go na swoim koncie jednym dotknięciem.",
    step6t: "Skanery i narzędzia", step6d: "Gold Killer, MTM V3.4 i Sensei X + codzienne DCA dla krypto i ETF-ów.",
    step7t: "Obejrzyj zajęcia na żywo", step7d: "Sesje z edukatorami MTM, kilka razy w tygodniu, w zakładce Na żywo.",
    step8t: "Zarezerwuj swoją rozmowę Onboarding", step8d: "30 min z zespołem, aby przygotować konto, automatyzację i plan nauki.",
    installTitle: "📲 Zainstaluj app",
    installIntro: "Wybierz swoją platformę:",
    installAppStore: "App Store (iPhone)", installTestflight: "Beta TestFlight",
    installApkNote: "(zezwól na \"nieznane źródła\")",
    installWebNote: "(bez instalowania czegokolwiek)",
    ctaCall: "📅 Zarezerwuj Onboarding (30 min)",
    footer: "Pytania?",
    footerMeeting: "zarezerwuj spotkanie",
    subject: "Twój onboarding MTM jest gotowy 🚀",
    preview: "Twój onboarding MTM jest gotowy — plan na 48 godzin.",
  },
  uk: {
    heading: "Ласкаво просимо до MoreThanMoney 👋",
    intro1a: "Твій onboarding готовий і працює. Виконуй кроки по порядку в ",
    intro1b: " і за 48 годин з'являться твої перші результати.",
    intro2: "Прийшов заради крипти, UGC чи social media? Починаєш одразу з learn while you earn — автоматизація й сповіщення працюють, поки ти досліджуєш свою сферу.",
    ctaOnboarding: "🚀 Переглянути мій Onboarding",
    planTitle: "⚡ Твій план на 48 годин",
    step1t: "Встанови app", step1d: "App Store, Android APK або Web App — акаунт той самий, завжди синхронізований.",
    step2t: "Створи акаунт і увійди", step2d: "3 дні Premium безкоштовно, без списань. Після завершення пробного періоду, 1-й місяць за 34,99€.",
    step3t: "Увімкни автоматизацію", step3d: "Автоматичне копіювання, Tap to Trade або Сповіщення — обери відповідний тобі режим.",
    step4t: "Налаштуй сповіщення", step4d: "Увімкни push-сповіщення стратегій (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Прийми Tap to Trade", step5d: "Отримуєш сигнал, переглядаєш деталі й виконуєш його у своєму акаунті одним дотиком.",
    step6t: "Сканери та інструменти", step6d: "Gold Killer, MTM V3.4 і Sensei X + щоденний DCA для крипти та ETF.",
    step7t: "Переглянь урок наживо", step7d: "Сесії з викладачами MTM, кілька разів на тиждень, у вкладці Наживо.",
    step8t: "Заброни свій Onboarding-дзвінок", step8d: "30 min з командою, щоб підготувати акаунт, автоматизацію та план навчання.",
    installTitle: "📲 Встанови app",
    installIntro: "Обери свою платформу:",
    installAppStore: "App Store (iPhone)", installTestflight: "Бета TestFlight",
    installApkNote: "(дозволь \"невідомі джерела\")",
    installWebNote: "(нічого не встановлюючи)",
    ctaCall: "📅 Забронювати Onboarding (30 min)",
    footer: "Питання?",
    footerMeeting: "заброни зустріч",
    subject: "Твій onboarding MTM готовий 🚀",
    preview: "Твій onboarding MTM готовий — план на 48 годин.",
  },
  tr: {
    heading: "MoreThanMoney'e hoş geldin 👋",
    intro1a: "Onboarding'in hazır ve çalışıyor. Adımları sırayla şurada takip et: ",
    intro1b: " ve 48 saat içinde ilk sonuçların gelmeye başlıyor.",
    intro2: "Kripto, UGC ya da social media için mi geldin? Hemen learn while you earn ile başlıyorsun — sen kendi alanını keşfederken otomasyon ve uyarılar çalışıyor.",
    ctaOnboarding: "🚀 Onboarding'imi gör",
    planTitle: "⚡ 48 saatlik planın",
    step1t: "app'i yükle", step1d: "App Store, Android APK veya Web App — hesap aynı, her zaman senkron.",
    step2t: "Hesabını oluştur ve giriş yap", step2d: "3 gün Premium ücretsiz, ödeme yok. Deneme bitince 1. ay 34,99€.",
    step3t: "Otomasyonu aç", step3d: "Otomatik kopyalama, Tap to Trade veya Uyarılar — sana uygun modu seç.",
    step4t: "Uyarıları ayarla", step4d: "Stratejilerin push bildirimlerini aç (Premium, Forex, Sensei, GoldKiller).",
    step5t: "Bir Tap to Trade'i kabul et", step5d: "Sinyali alırsın, detayları gözden geçirir ve tek dokunuşla kendi hesabında uygularsın.",
    step6t: "Tarayıcılar ve Araçlar", step6d: "Gold Killer, MTM V3.4 ve Sensei X + kripto ve ETF için günlük DCA.",
    step7t: "Canlı bir ders izle", step7d: "MTM eğitmenleriyle oturumlar, haftada birkaç kez, Canlı sekmesinde.",
    step8t: "Onboarding görüşmeni ayarla", step8d: "Hesabı, otomasyonu ve çalışma planını hazırlamak için ekiple 30 min.",
    installTitle: "📲 app'i yükle",
    installIntro: "Platformunu seç:",
    installAppStore: "App Store (iPhone)", installTestflight: "TestFlight Beta",
    installApkNote: "(\"bilinmeyen kaynaklar\"a izin ver)",
    installWebNote: "(hiçbir şey yüklemeden)",
    ctaCall: "📅 Onboarding ayarla (30 min)",
    footer: "Sorular?",
    footerMeeting: "bir toplantı ayarla",
    subject: "MTM onboarding'in hazır 🚀",
    preview: "MTM onboarding'in hazır — 48 saatlik plan.",
  },
}
