/**
 * O CATÁLOGO, COMO ELE É — a fotografia de `funded_symbols` que os gates de conformidade usam.
 *
 * Estava dentro de `cripto-catalogo.check.ts`. Saiu para aqui quando passou a haver um SEGUNDO
 * teste a precisar da mesma tabela (`cripto-espelhos.check.ts`, que compara as três cópias da
 * regra). Duas fotografias do catálogo seria duas verdades — e o ponto todo deste ficheiro é
 * haver uma só.
 *
 * Um símbolo novo no catálogo que estas listas não conheçam é um símbolo que ninguém confirmou
 * que o gate apanha.
 */
/** `select symbol from funded_symbols where ativo and classe = 'cripto'` — 24/09/2026. */
export const CRIPTO = 'ADAJPY,ADAUSD,ALGUSD,ATMUSD,AVAUSD,BATUSD,BCHJPY,BCHUSD,BNBUSD,BTCBCH,BTCETH,BTCEUR,BTCJPY,BTCLTC,BTCUSD,BTCXAU,CROUSD,CRVUSD,DOGUSD,DOTUSD,EOSUSD,ETCUSD,ETHBCH,ETHEUR,ETHJPY,ETHLTC,ETHUSD,ETHXAU,FILUSD,GRTUSD,HYPEUSD,INCUSD,IOTUSD,LNKUSD,LRCUSD,LTCJPY,LTCUSD,NEOUSD,NERUSD,NXPCUSD,OKBUSD,SANUSD,SHBUSD,SKYUSD,SOLJPY,SOLUSD,SUSUSD,TRUMPUSD,TRXUSD,UNIUSD,USDTJPY,WLDUSD,WLFIUSD,XLMJPY,XLMUSD,XRPJPY,XRPUSD,XTZUSD,ZECUSD'.split(',')

/** As outras classes, menos as acções (essas vão numa amostra, abaixo). */
export const FOREX = 'AUDCAD,AUDCHF,AUDJPY,AUDNZD,AUDSGD,AUDUSD,CADCHF,CADJPY,CHFJPY,EURAUD,EURCAD,EURCHF,EURCZK,EURDKK,EURGBP,EURHUF,EURJPY,EURNZD,EURSGD,EURUSD,GBPAUD,GBPCAD,GBPCHF,GBPJPY,GBPNZD,GBPSGD,GBPUSD,NZDCAD,NZDCHF,NZDJPY,NZDSGD,NZDUSD,SGDJPY,USDBRL,USDCAD,USDCHF,USDCLP,USDCOP,USDCZK,USDDKK,USDHUF,USDIDR,USDILS,USDINR,USDJPY,USDKRW,USDMXN,USDNOK,USDSEK,USDSGD,USDTHB,USDTWD,USDZAR'.split(',')
export const METAL = 'GAUUSD,XAGUSD,XAUEUR,XAUJPY,XAUUSD,XPDUSD,XPTUSD'.split(',')
export const INDICE = 'BVSPX,CHINA50,CHINA50FT,CHINAH,DJ30FT,ES35,EU50,FRA40,FRA40FT,GER40,GER40FT,HK50,HK50FT,HKTECH,JPN225,JPN225FT,NAS100,NAS100FT,NETH25,SGP20,SP500FT,SPI200,SWI20,TWINDEX,UK100,UK100FT,US2000,US30,US500,USDX,VIX'.split(',')
export const ENERGIA = 'CL-OIL,GAS,GASOIL,NG,UKOIL,UKOUSDFT,USOIL,WHEAT'.split(',')
export const COMMODITY = 'COCOA,COFFEE,COPPER,COTTON,OJ,SOYBEAN,SUGAR'.split(',')
export const OBRIGACAO = 'EUB10Y,EUB2Y,EUB30Y,EUB5Y,EURIBOR3M,LONGGILT,USNOTE10Y'.split(',')
/** ETF: sem os de bitcoin, que estão à parte. */
export const ETF = 'DBC,DRAM,DRAMUSD,DXYZ,EEM,EFA,EWJ,EWJUSD,EWT,EWTUSD,EWY,EWYUSD,EWZ,EWZUSD,FDN,FOTO,FXI,GDX,GDXJ,GLD,ICLN,IGV,INDA,IWM,IWMUSD,IYW,MCHI,NASA,OIH,QCLN,QQQ,QQQUSD,SMH,SOXL,SOXLUSD,SOXX,SPY,SPYUSD,TAN,TLT,TQQQ,UNG,URNMUSD,USL,USO,UVXYUSD,VCX,VGT,XLEUSD,XLF,XLK,XOP,BNO,GOEX'.split(',')
/**
 * Acções com as letras que mais se parecem com as abreviaturas de cripto do catálogo (ALG/ATM/
 * AVA/SAN/NEO/DOG/LNK/OKB/EOS/BAT/CRV/GRT/SKY/INC/IOT). São estas que um gate largo demais apanha.
 */
export const ACOES = 'A,AA,AALG,AAPL,AAPLUSD,ADBEUSD,ALB,ALGN,AMD,AMT,AMZNUSD,ASMLUSD,AVGO,AVGOUSD,BAC,BRKBUSD,CRM,CRWD,CRWDUSD,DOCN,DOCU,EOG,GOOGLUSD,IBM,IBMUSD,IONQ,IOVA,METAUSD,MSFTUSD,NEMD,NET,NFLXUSD,NVDAUSD,NXPI,OKE,OKLO,OKTA,ORCLUSD,PLTRUSD,QCOMUSD,SKHY,SNDKUSD,SPCXUSD,TSLAUSD,TSMUSD,UBERUSD,WDCUSD,WMTUSD,ZMUSD'.split(',')

/** Tudo o que NÃO é cripto: um falso positivo aqui tira ouro ou forex a quem tem direito a eles. */
export const NAO_CRIPTO = [...FOREX, ...METAL, ...INDICE, ...ENERGIA, ...COMMODITY, ...OBRIGACAO, ...ETF, ...ACOES]

/** O catálogo inteiro, sem repetidos — a tabela que se corre pelas três cópias da regra. */
export const TODOS = [...new Set([...CRIPTO, ...NAO_CRIPTO])]
